name: christopherl
favicon: null
layout_spectrum: 0.3699154064524919
typography_spectrum: 0.26433349773287773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 0.30786198284476995
  saturation: 0.5970977144315839
  rhythmicContrast: 0.742017128970474
purpose: []
