name: christopherl
favicon: null
layout_spectrum: 0.48872
typography_spectrum: 0.374552
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-51281227-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111518'
    - '#dcccb3'
    - '#cb6245'
    - '#7b291e'
    - '#3e5b7d'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
