name: christopherl
favicon: null
layout_spectrum: 0.25125
typography_spectrum: 0.13534
title: Est. 2016
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-51281227-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c418a'
    - '#1d68ad'
    - '#fde5e8'
    - '#d8ced6'
    - '#9fa7bb'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
